### ISSUE TITLE
Uniy integration issues

### ISSUE THREAD

**Issue by kronnect** [boxqkrtm/com.unity.ide.cursor#2]
When plugin opens CursorAI code, some errors are shown in the console:
<img width="1285" alt="imagen" src="https://github.com/user-attachments/assets/68591772-4dc9-4b0e-a35f-d113ec435a42">

**Comment by boxqkrtm** [comment]
I Added .meta to that folders.
Please let me know the results after updating
Thanks.

**Comment by kronnect** [comment]
Thank you but some console errors still appear:
<img width="1271" alt="image" src="https://github.com/user-attachments/assets/3695a6d0-67e7-4153-acb4-5461bb915514">

These errors appear when importing the plugin on Mac and also when opening or building the project.

**Comment by kronnect** [comment]
I fixed it by moving the AppleEventIntegration.bundle to a non-mutable folder in the project. Unity adds/fixes the .meta files and then moving it back to its original folder. Attached's the fixed bundle with .meta files:
[AppleEventIntegration.zip](https://github.com/user-attachments/files/17322836/AppleEventIntegration.zip)

**Comment by boxqkrtm** [comment]
I checked the log and found that I had misread the cause. Correction work will be carried out soon.
